--- #YAML:1.0
name:                Devel-Hook
version:             0.005
abstract:            Mess around with BEGIN/CHECK/INIT/END blocks
license:             perl
author:              
    - Adriano Ferreira <ferreira@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    strict:                        0
    Test::More:                    0
    warnings:                      0
    XSLoader:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
recommends:
    Test::Pod:                     1.18
    Test::Pod::Coverage:           1.04
